language: ruby
rvm:
  - 2.6

sudo: required

env:
  - JEKYLL_ENV=production

before_script:
  - node -v
  # update npm
  - npm install npm -g

script:
  - npm install
  - npx webpack
  - bundle install
  - bundle exec jekyll build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: _site/
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
